name: 'Java Lint'

on: [push]

jobs:
  Lint:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Java
      run: |
        #!/bin/bash

        # Created by Bat.bat(williambj1) on Jan 26, 2020

        # Repo Path
        RepoPath="$(cd "$(dirname "$1")"; pwd -P)/$(basename "$1")"

        # Exit on Network Issue
        function networkErr() {
            echo "[ ERROR ]: Failed to download resources from ${URL}, please check your connection!"
            exit 1
        }

        # Install PMD
        function Install() {
            cd $HOME
            curl -#OL https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.21.0/pmd-bin-6.21.0.zip >/dev/null 2>&1
            unzip "*.zip" >/dev/null 2>&1
            rm -rf pmd-bin*.zip >/dev/null 2>&1
            MatchDir="$(cd "$(dirname $HOME/pmd-bin*)"; pwd -P)/$(basename $HOME/pmd-bin*)"
            mkdir rulesets
            cd rulesets
            mkdir java
            cd java
            cd $HOME
            echo ""
            echo '=========== Lint Check ============'
            echo ""
            ${MatchDir}/bin/run.sh pmd -d $RepoPath -no-cache -R $RepoPath/.github/jpinpoint-rules.xml -f text
            echo ""
            echo '========== End Check =============='
        }

        function main() {
            Install
        }
        main

