name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Java
      run: |
        #!/bin/bash

        # Created by Bat.bat(williambj1) on Jan 26, 2020

        # Repo Path
        RepoPath="$(cd "$(dirname "$1")"; pwd -P)/$(basename "$1")"

        # Exit on Network Issue
        function networkErr() {
            echo "[ ERROR ]: Failed to download resources from ${URL}, please check your connection!"
            exit 1
        }

        # Download GitHub Release
        function DGR() {
            cd $HOME
            local rawURL="https://api.github.com/repos/$1/$2/releases/latest"
            local URL="$(curl --silent "${rawURL}" | grep 'browser_download_url' | grep 'pmd-bin' | tr -d '"' | tr -d ' ' | sed -e 's/browser_download_url://')"
            curl -# -L -O "${URL}" >/dev/null 2>&1 || networkErr
        }

        # Install PMD
        function Install() {
            cd $HOME
            unzip "*.zip" >/dev/null 2>&1
            rm -rf pmd-bin*.zip >/dev/null 2>&1
            MatchDir="$(cd "$(dirname $HOME/pmd-bin*)"; pwd -P)/$(basename $HOME/pmd-bin*)"
            mkdir rulesets
            cd rulesets
            mkdir java
            cd java
            curl -# -L -O https://raw.githubusercontent.com/jborgers/PMD-jPinpoint-rules/master/rulesets/java/jpinpoint-rules.xml >/dev/null 2>&1
            cd $HOME
            ${MatchDir}/bin/run.sh pmd -d $RepoPath -R rulesets/java/jpinpoint-rules.xml -f text
        }

        function main() {
            DGR pmd pmd
            Install
        }
        main

